if(location.protocol==='file:'){location.href='http://localhost:3000/#shop'}
let products=[
 {id:1,name:'Narayanpeta Buttis',category:'Dress Materials',price:1299,mrp:1699,colors:['#8c3038','#d4a461'],tag:'Bestseller'},
 {id:2,name:'Gulab Handloom Saree',category:'Sarees',price:2890,mrp:3490,colors:['#b76b57','#eed2a7'],tag:'New'},
 {id:3,name:'Mogra Cotton Kurti',category:'Kurtis',price:1490,mrp:1890,colors:['#b4aa94','#6f7764'],tag:''},
 {id:4,name:'Meher Chanderi Dupatta',category:'Dupattas',price:990,mrp:1290,colors:['#6d1e2e','#d4b27c'],tag:'New'},
 {id:5,name:'Rangoli Silk Saree',category:'Sarees',price:3290,mrp:4190,colors:['#4d526d','#d2a866'],tag:''},
 {id:6,name:'Noor Embroidered Kurta',category:'Kurtis',price:1790,mrp:2190,colors:['#c28b76','#f1d7bc'],tag:''},
 {id:7,name:'Ira Blockprint Set',category:'Dress Materials',price:1890,mrp:2390,colors:['#65715a','#e5c09b'],tag:'Bestseller'},
 {id:8,name:'Kali Zari Dupatta',category:'Dupattas',price:1190,mrp:1490,colors:['#aa6b41','#e5b974'],tag:''}
];
const fallbackSkus=['NP-DM-001','GL-SR-002','MG-KR-003','MH-DP-004','RS-SS-005','NK-KR-006','IB-DS-007','KZ-DP-008'];
products=products.map((p,i)=>({...p,id:fallbackSkus[i],sku:fallbackSkus[i]}));
/* Preserve image fields from API and render saved images. */
(()=>{const urls=p=>{let a=[];try{a=Array.isArray(p.image_urls)?p.image_urls:JSON.parse(p.image_urls||'[]')}catch(e){}return (a.length?a:(p.image_url?[p.image_url]:[])).filter(Boolean)};const paint=()=>document.querySelectorAll('.product-card').forEach(c=>{const b=c.querySelector('[data-add]'),p=products.find(x=>String(x.id)===String(b&&b.dataset.add)),a=urls(p),box=c.querySelector('.product-image'),art=box&&box.querySelector('.product-art');if(!p||!a.length||!box||!art)return;const im=document.createElement('img');im.src=a[0];im.alt=p.name;im.style='width:100%;height:100%;object-fit:cover;display:block';art.replaceWith(im)});const load=async()=>{try{const r=await fetch('/api/products',{cache:'no-store'}),rows=await r.json();if(!Array.isArray(rows)||!rows.length)return;products=rows.map((p,i)=>({id:p.sku||p.id,sku:p.sku,name:p.name,category:p.category||'Vastra edit',price:Number(p.price),mrp:Number(p.mrp||p.price),stock:Number(p.stock||0),image_url:p.image_url,image_urls:p.image_urls,colors:[['#8c3038','#d4a461'],['#b76b57','#eed2a7'],['#b4aa94','#6f7764'],['#6d1e2e','#d4b27c']][i%4],tag:i<2?'New':''})).filter(p=>p.status!=='disabled');renderProducts();paint()}catch(e){}};setInterval(load,2000);load()})();

let activeCategory='All', cart=JSON.parse(localStorage.getItem('vastra-cart')||'[]'), wishlist=JSON.parse(localStorage.getItem('vastra-wishlist')||'[]').filter(x=>x&&x!=='undefined'&&x!=='NaN');
fetch('https://trnzlkcdjjltphkknrqv.supabase.co/rest/v1/products?select=*&status=eq.active&order=created_at.desc',{headers:{apikey:'sb_publishable_NaR11hPva6us_0wX2fNamA_PWJ_YFR8',Authorization:'Bearer sb_publishable_NaR11hPva6us_0wX2fNamA_PWJ_YFR8'}}).then(r=>r.ok?r.json():[]).then(rows=>{if(rows.length){products=rows.map((p,i)=>({id:p.sku||p.id,sku:p.sku,name:p.name,category:p.category||'Vastra edit',price:Number(p.price),mrp:Number(p.mrp),image_url:p.image_url,image_urls:p.image_urls,colors:[['#8c3038','#d4a461'],['#b76b57','#eed2a7'],['#b4aa94','#6f7764'],['#6d1e2e','#d4b27c']][i%4],tag:i<2?'New':''}));renderProducts();updateCart()}}).catch(()=>{});
const money=n=>'₹'+n.toLocaleString('en-IN');
function decorateProductGalleries(){document.querySelectorAll('.product-card').forEach(card=>{if(card.querySelector('.card-gallery'))return;const id=card.querySelector('[data-add]')?.dataset.add,p=products.find(x=>String(x.id)===String(id));if(!p)return;let urls=[];try{urls=Array.isArray(p.image_urls)?p.image_urls:JSON.parse(p.image_urls||'[]')}catch(e){}if(!urls.length&&p.image_url)urls=[p.image_url];if(urls.length<2)return;const box=card.querySelector('.product-image'),art=box.querySelector('.product-art');if(!box||!art)return;const gallery=document.createElement('div');gallery.className='card-gallery';gallery.innerHTML=urls.map((u,i)=>`<img class="card-gallery-image ${i?'':'active'}" src="${u}" alt="${p.name}">`).join('')+`<button type="button" class="card-gallery-prev">‹</button><button type="button" class="card-gallery-next">›</button><span class="card-gallery-count">1/${urls.length}</span>`;art.replaceWith(gallery);let current=0;const show=d=>{current=(current+d+urls.length)%urls.length;gallery.querySelectorAll('.card-gallery-image').forEach((x,i)=>x.classList.toggle('active',i===current));gallery.querySelector('.card-gallery-count').textContent=`${current+1}/${urls.length}`};gallery.querySelector('.card-gallery-prev').onclick=e=>{e.stopPropagation();show(-1)};gallery.querySelector('.card-gallery-next').onclick=e=>{e.stopPropagation();show(1)}})}
function renderProducts(){let list=products.filter(p=>activeCategory==='All'||p.category===activeCategory);const sort=document.querySelector('#sortSelect').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);document.querySelector('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><div class="product-art" style="--p:${p.colors[0]};--q:${p.colors[1]}"></div><button class="heart ${wishlist.some(x=>String(x)===String(p.id))?'active':''}" data-wish="${p.id}">${wishlist.some(x=>String(x)===String(p.id))?'♥':'♡'}</button>${p.tag?`<span class="tag">${p.tag}</span>`:''}</div><div class="product-meta"><div><div class="product-name">${p.name}</div><div class="product-category">${p.category} · ★ 4.8</div></div><div class="product-price">${money(p.price)}<span class="mrp">${money(p.mrp)}</span></div></div><button class="quick-add" data-add="${p.id}">Quick add +</button></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(b.dataset.wish));}
function save(){localStorage.setItem('vastra-cart',JSON.stringify(cart));localStorage.setItem('vastra-wishlist',JSON.stringify(wishlist));updateCart();}
function add(id){const found=cart.find(x=>x.id===id);found?found.qty++:cart.push({id,qty:1});save();toast('Added to your bag');}
function toggleWish(id){const key=String(id);wishlist=wishlist.some(x=>String(x)===key)?wishlist.filter(x=>String(x)!==key):[...wishlist,key];save();renderProducts();toast(wishlist.some(x=>String(x)===key)?'Saved to wishlist':'Removed from wishlist');}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#drawerCount').textContent=count;const items=document.querySelector('#cartItems');if(!cart.length){items.innerHTML='<div class="empty">Your bag is waiting.<br><a href="#shop">Discover the edit →</a></div>';document.querySelector('#cartTotal').textContent='₹0';return}let total=0;items.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);total+=p.price*x.qty;return `<div class="cart-item"><div class="cart-thumb" style="--p:${p.colors[0]}"></div><div><h4>${p.name}</h4><small>${p.category} · ${money(p.price)}</small><div class="qty"><button data-dec="${p.id}">−</button>${x.qty}<button data-inc="${p.id}">+</button><button class="remove" data-remove="${p.id}">Remove</button></div></div></div>`}).join('');document.querySelector('#cartTotal').textContent=money(total);items.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>change(+b.dataset.inc,1));items.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>change(+b.dataset.dec,-1));items.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);save()});}
function change(id,delta){const x=cart.find(y=>y.id===id);x.qty+=delta;if(x.qty<1)cart=cart.filter(y=>y.id!==id);save()}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openCart(){document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#overlay').classList.add('show')};function closeCart(){document.querySelector('#cartDrawer').classList.remove('open');document.querySelector('#overlay').classList.remove('show')}
document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#closeCart').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#sortSelect').onchange=renderProducts;document.querySelector('#filterBtn').onclick=()=>document.querySelector('#filterRow').classList.toggle('open');document.querySelectorAll('.filter-row button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.cat;renderProducts()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.filter;document.querySelectorAll('.filter-row button').forEach(x=>x.classList.toggle('active',x.dataset.cat===activeCategory));renderProducts()});document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();document.querySelector('#newsletterMsg').textContent='You’re on the list — welcome to Vastra.';e.target.reset()};document.querySelector('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Your bag is empty');toast('Checkout is ready for Razorpay + COD setup')};renderProducts();updateCart();
document.body.insertAdjacentHTML('beforeend','<div class="modal" id="detailModal"><div class="modal-card" id="detailContent"></div></div><div class="modal" id="checkoutModal"><div class="modal-card checkout-card"><button class="close-btn modal-close">×</button><p class="eyebrow">SECURE CHECKOUT</p><h2>Complete your order.</h2><form id="checkoutForm"><label>Full name<input required name="name" placeholder="Your name"></label><label>Email address<input required type="email" name="email" placeholder="you@example.com"></label><label>Delivery address<textarea required name="address" placeholder="House no., street, city, state"></textarea></label><label>Pincode<input required pattern="[0-9]{6}" name="pincode" placeholder="6-digit pincode"></label><p class="eyebrow">PAYMENT METHOD</p><label><input type="radio" name="payment" value="cod" checked> Cash on Delivery</label><label><input type="radio" name="payment" value="razorpay"> Razorpay (integration ready)</label><button class="btn btn-dark full">Place order <span>→</span></button><small class="muted">Totals, stock and payment status must be verified server-side.</small></form></div></div>');
function openDetail(id){const p=products.find(x=>x.id===id);document.querySelector('#detailContent').innerHTML='<button class="close-btn modal-close">×</button><div class="detail-layout"><div class="detail-visual" style="--p:'+p.colors[0]+';--q:'+p.colors[1]+'"><div class="product-art"></div></div><div class="detail-copy"><p class="eyebrow">'+p.category.toUpperCase()+' · VASTRA</p><h2>'+p.name+'</h2><p class="product-rating">★ 4.8 · 24 reviews</p><div class="detail-price">'+money(p.price)+' <span>'+money(p.mrp)+'</span> <b>'+Math.round((1-p.price/p.mrp)*100)+'% off</b></div><p class="detail-description">A considered piece made for celebration and everyday ritual. Finished with a soft handfeel, thoughtful detail and the unmistakable character of Indian craft.</p><div class="detail-specs"><span>Fabric <b>Premium cotton blend</b></span><span>Dispatch <b>Within 2–3 days</b></span></div><button class="btn btn-dark full" data-detail-add="'+p.id+'">Add to bag <span>→</span></button></div></div>';document.querySelector('#detailModal').classList.add('show');document.querySelectorAll('.modal-close').forEach(x=>x.onclick=()=>document.querySelector('#detailModal').classList.remove('show'));document.querySelector('[data-detail-add]').onclick=()=>{add(id);document.querySelector('#detailModal').classList.remove('show')}}
document.querySelector('#productGrid').addEventListener('click',e=>{const card=e.target.closest('.product-card');if(card&&!e.target.closest('button'))openDetail(+card.querySelector('[data-add]').dataset.add)});
document.querySelector('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Your bag is empty');closeCart();document.querySelector('#checkoutModal').classList.add('show')};document.querySelector('#checkoutModal').addEventListener('click',e=>{if(e.target.id==='checkoutModal'||e.target.closest('.modal-close'))document.querySelector('#checkoutModal').classList.remove('show')});document.querySelector('#checkoutForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),items=cart.map(x=>{const p=products.find(y=>y.id===x.id);return {id:p.id,sku:p.sku||p.id,name:p.name,quantity:x.qty}}),r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,paymentMethod:f.get('payment'),customer:{name:f.get('name'),email:f.get('email'),address:f.get('address'),pincode:f.get('pincode')}})});if(!r.ok)return toast('Unable to place order — please try again');cart=[];save();document.querySelector('#checkoutModal').classList.remove('show');toast('Order received — thank you for choosing Vastra')};
function applyStockLabels(){document.querySelectorAll('.product-card').forEach(card=>{const button=card.querySelector('[data-add]'),p=products.find(x=>String(x.id)===button?.dataset.add);if(!p||!button)return;let label=card.querySelector('.stock-label');if(p.stock<=0){button.disabled=true;button.textContent='Out of stock';button.classList.add('disabled');if(!label){label=document.createElement('span');label.className='stock-label';label.textContent='Out of stock';card.querySelector('.product-image')?.appendChild(label)}}else{button.disabled=false;button.textContent='Quick add +';label?.remove()}})}setInterval(applyStockLabels,500);applyStockLabels();
async function syncLocalCatalog(){try{const rows=await fetch('/api/products',{cache:'no-store'}).then(r=>r.json());if(!Array.isArray(rows)||!rows.length)return;products=rows.map((p,i)=>({id:Number(p.id)||i+1,sku:p.sku,name:p.name,category:p.category||'Vastra edit',price:Number(p.price),mrp:Number(p.mrp||p.price),stock:Number(p.stock||0),colors:[['#8c3038','#d4a461'],['#b76b57','#eed2a7'],['#b4aa94','#6f7764'],['#6d1e2e','#d4b27c']][i%4],tag:i<2?'New':''})).filter(p=>p.status!=='disabled');renderProducts();updateCart()}catch(e){}}setInterval(syncLocalCatalog,2000);syncLocalCatalog();
let lastCatalogSignature='';async function syncLocalCatalogStable(){try{const rows=await fetch('/api/products',{cache:'no-store'}).then(r=>r.json());if(!Array.isArray(rows)||!rows.length)return;const signature=JSON.stringify(rows.map(p=>[p.id,p.name,p.price,p.stock,p.status,p.category]));if(signature===lastCatalogSignature)return;lastCatalogSignature=signature;products=rows.map((p,i)=>({id:Number(p.id)||i+1,sku:p.sku,name:p.name,category:p.category||'Vastra edit',price:Number(p.price),mrp:Number(p.mrp||p.price),stock:Number(p.stock||0),colors:[['#8c3038','#d4a461'],['#b76b57','#eed2a7'],['#b4aa94','#6f7764'],['#6d1e2e','#d4b27c']][i%4],tag:i<2?'New':''})).filter(p=>p.status!=='disabled');renderProducts();updateCart()}catch(e){}}clearInterval(window.vastraCatalogTimer);window.vastraCatalogTimer=setInterval(syncLocalCatalogStable,2000);syncLocalCatalogStable();
syncLocalCatalog=syncLocalCatalogStable;
syncLocalCatalog=async()=>{};
applyStockLabels=()=>{};
function cleanOutOfStockCards(){document.querySelectorAll('.product-card').forEach(card=>{const b=card.querySelector('.quick-add');if(b&&b.disabled){const tag=card.querySelector('.tag');if(tag)tag.style.display='none';b.style.display='none';let label=card.querySelector('.stock-label');if(!label){label=document.createElement('span');label.className='stock-label';label.textContent='Out of stock';card.querySelector('.product-image')?.appendChild(label)}}})}setInterval(cleanOutOfStockCards,300);cleanOutOfStockCards();
const stockObserver=new MutationObserver(()=>{document.querySelectorAll('.product-card').forEach(card=>{const button=card.querySelector('[data-add]'),id=button?.dataset.add,p=products.find(x=>String(x.id)===String(id));if(p&&Number(p.stock)<=0){card.querySelector('.tag')?.remove();button?.remove();let label=card.querySelector('.stock-label');if(!label){label=document.createElement('span');label.className='stock-label';label.textContent='Out of stock';card.querySelector('.product-image')?.appendChild(label)}}})});stockObserver.observe(document.querySelector('#productGrid')||document.body,{childList:true,subtree:true});
async function forceApiStockState(){try{const rows=await fetch('/api/products',{cache:'no-store'}).then(r=>r.json());document.querySelectorAll('.product-card').forEach((card,index)=>{const p=rows[index];if(!p||Number(p.stock)>0)return;card.querySelector('.tag')?.remove();card.querySelector('.quick-add')?.remove();card.querySelector('.heart')?.insertAdjacentHTML('afterend','<span class="stock-label">Out of stock</span>')})}catch(e){}}setInterval(forceApiStockState,100);forceApiStockState();
forceApiStockState=()=>{};function normalizeStockLabels(){document.querySelectorAll('.product-card').forEach(card=>{const labels=card.querySelectorAll('.stock-label');if(labels.length>1){labels.forEach((x,i)=>{if(i>0)x.remove()})}})}setInterval(normalizeStockLabels,250);normalizeStockLabels();
const accountButton=document.querySelector('.header-actions .icon-btn:not(#wishlistBtn)');if(accountButton){accountButton.id='accountBtn';accountButton.onclick=()=>{let panel=document.querySelector('#profilePanel');if(panel){panel.remove();return}document.body.insertAdjacentHTML('beforeend','<section class="profile-panel" id="profilePanel"><button class="close-btn" id="closeProfile">×</button><p class="eyebrow">YOUR VASTRA PROFILE</p><h3>Welcome back.</h3><p>Save your details for faster checkout and view your orders here.</p><label>Email<input type="email" id="profileEmail" placeholder="you@example.com"></label><label>Name<input id="profileName" placeholder="Your name"></label><button class="btn btn-dark" id="saveProfile">Save profile</button><p id="profileMsg"></p></section>');closeProfile.onclick=()=>panel.remove();saveProfile.onclick=()=>{localStorage.setItem('vastra_profile',JSON.stringify({email:profileEmail.value,name:profileName.value}));profileMsg.textContent='Profile saved successfully.'};const saved=JSON.parse(localStorage.getItem('vastra_profile')||'{}');profileEmail.value=saved.email||'';profileName.value=saved.name||''}}
document.querySelector('#productGrid')?.addEventListener('click',e=>{const card=e.target.closest('.product-card');if(!card||e.target.closest('button'))return;const p=products.find(x=>String(x.id)===card.querySelector('[data-add]')?.dataset.add);if(p?.sku){e.preventDefault();e.stopImmediatePropagation();location.href='/product.html?sku='+encodeURIComponent(p.sku)}},true);
const searchTrigger=document.querySelector('.search-trigger');if(searchTrigger){searchTrigger.onclick=()=>{let panel=document.querySelector('#searchPanel');if(panel){panel.remove();return}document.body.insertAdjacentHTML('beforeend','<section class="search-panel" id="searchPanel"><div class="search-box"><input id="searchInput" placeholder="Search sarees, kurtis…" autofocus><button id="closeSearch">×</button></div><div id="searchSuggestions"><p>Popular searches</p><button data-query="Sarees">Sarees for women</button><button data-query="Kurtis">Cotton kurtis</button><button data-query="Dupattas">Dupattas</button></div></section>');closeSearch.onclick=()=>panel.remove();searchInput.oninput=()=>{const q=searchInput.value.toLowerCase();searchSuggestions.innerHTML=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q)).slice(0,6).map(p=>'<a href="/product.html?sku='+encodeURIComponent(p.sku||'')+'">'+p.name+' <span>→</span></a>').join('')||'<p>No products found</p>'};document.querySelectorAll('#searchSuggestions [data-query]').forEach(b=>b.onclick=()=>{searchInput.value=b.dataset.query;searchInput.dispatchEvent(new Event('input'))})}}
if(searchTrigger){searchTrigger.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();document.querySelector('#searchPanel')?.remove();document.body.insertAdjacentHTML('beforeend','<section class="search-panel inline-search" id="searchPanel"><div class="search-box"><span class="search-icon">⌕</span><input id="searchInput" placeholder="Search products or categories…" autofocus><button id="closeSearch">×</button></div><div class="keyword-tags"><span>Popular:</span><button data-keyword="Sarees">Sarees</button><button data-keyword="Kurtis">Kurtis</button><button data-keyword="Dupattas">Dupattas</button><button data-keyword="Dress Materials">Dress Materials</button></div><div id="searchSuggestions"><p>Type to search products</p></div></section>');const panel=document.querySelector('#searchPanel');closeSearch.onclick=()=>panel.remove();const show=()=>{const q=searchInput.value.toLowerCase().trim();searchSuggestions.innerHTML=q?products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q)).slice(0,8).map(p=>'<a href="/product.html?sku='+encodeURIComponent(p.sku||'')+'"><span>'+p.name+'</span><small>'+p.category+' · ₹'+p.price+'</small><b>→</b></a>').join('')||'<p>No matching products</p>':'<p>Type to search products</p>';};searchInput.oninput=show;panel.querySelectorAll('[data-keyword]').forEach(b=>b.onclick=()=>{searchInput.value=b.dataset.keyword;show();searchInput.focus()})}}
(()=>{const old=document.querySelector('.search-trigger');if(!old||old.dataset.inlineReady)return;old.dataset.inlineReady='1';const wrap=document.createElement('div');wrap.className='header-search-inline';wrap.innerHTML='<span>⌕</span><input id="headerSearchInput" placeholder="Search"><div id="headerSearchResults"></div>';old.replaceWith(wrap);const input=wrap.querySelector('input'),results=wrap.querySelector('#headerSearchResults');input.oninput=()=>{const q=input.value.toLowerCase().trim();if(!q){results.classList.remove('open');return}const matches=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q)).slice(0,6);results.innerHTML=matches.map(p=>'<a href="/product.html?sku='+encodeURIComponent(p.sku||'')+'"><span>'+p.name+'</span><small>'+p.category+' · ₹'+p.price+'</small><b>→</b></a>').join('')||'<p>No products found</p>';results.classList.add('open')};document.addEventListener('click',e=>{if(!wrap.contains(e.target))results.classList.remove('open')})})();
if(accountButton){accountButton.onclick=e=>{e.preventDefault();document.querySelector('#accountMenu')?.remove();document.body.insertAdjacentHTML('beforeend','<section class="account-menu" id="accountMenu"><div class="account-welcome"><b>Welcome</b><span>To access account and manage orders</span><button class="login-signup">LOGIN / SIGNUP</button></div><div class="account-links"><a href="/admin#orders">Orders</a><a href="#shop">Wishlist</a><a href="#">Gift Cards</a><a href="#">Contact Us</a><a href="#">Vastra Insider <em>New</em></a></div><div class="account-links"><a href="#">Vastra Credit</a><a href="#">Coupons</a><a href="#">Saved Cards</a><a href="#">Saved VPA</a><a href="#">Saved Addresses</a></div></section>');document.querySelector('.login-signup').onclick=()=>location.href='/login';setTimeout(()=>document.addEventListener('click',function close(e){const m=document.querySelector('#accountMenu');if(m&&!m.contains(e.target)&&e.target!==accountButton){m.remove();document.removeEventListener('click',close)}}),0)}}
if(accountButton){accountButton.onclick=e=>{e.preventDefault();document.querySelector('#accountMenu')?.remove();const profile=JSON.parse(localStorage.getItem('vastra_profile')||'{}'),id=profile.email||localStorage.getItem('vastra_login_identifier')||'';const logged=localStorage.getItem('vastra_authenticated')==='true';const name=profile.name||((id.includes('@')?id.split('@')[0]:'Anil'));document.body.insertAdjacentHTML('beforeend',logged?'<section class="account-menu" id="accountMenu"><div class="account-welcome"><b>Hello '+name+'</b><span>'+id+'</span></div><div class="account-links"><a href="/profile">Profile Details</a><a href="/admin#orders">Orders</a><a href="#">Wishlist</a><a href="#">Gift Cards</a><a href="#">Contact Us</a></div><div class="account-links"><a href="#">Vastra Credit</a><a href="#">Coupons</a><a href="#">Saved Cards</a><a href="#">Saved Addresses</a></div><div class="account-links"><a href="/profile">Edit Profile</a><a href="/login" onclick="localStorage.removeItem(\'vastra_authenticated\')">Logout</a></div></section>':'<section class="account-menu" id="accountMenu"><div class="account-welcome"><b>Welcome</b><span>To access account and manage orders</span><button class="login-signup" onclick="location.href=\'/login\'">LOGIN / SIGNUP</button></div></section>')}}
document.addEventListener('click',e=>{const link=e.target.closest('a[href="/admin#orders"]');if(link){e.preventDefault();location.href='/orders'}});
document.addEventListener('click',e=>{const a=e.target.closest('#accountMenu a');if(!a)return;const key=(a.textContent||'').trim().toLowerCase();const map={coupons:'coupons', 'vastra credit':'credit','saved cards':'cards','saved addresses':'addresses'};if(map[key]){e.preventDefault();location.href='/account.html?section='+map[key]}});
document.addEventListener('click',e=>{const menu=document.querySelector('#accountMenu');const button=document.querySelector('#accountBtn,.account-trigger,[data-account]');if(menu&&!menu.contains(e.target)&&!button?.contains(e.target)){menu.remove()}});
/* Final account trigger binding: keep the profile icon reliable after dynamic header updates. */
(()=>{const button=document.querySelector('#accountBtn')||document.querySelector('.header-actions .icon-btn:not(#wishlistBtn)');if(!button)return;button.id='accountBtn';button.type='button';button.onclick=(e)=>{e.preventDefault();e.stopPropagation();const open=document.querySelector('#accountMenu');if(open){open.remove();return}const profile=JSON.parse(localStorage.getItem('vastra_profile')||'{}'),id=profile.email||profile.mobile||localStorage.getItem('vastra_login_identifier')||'',logged=localStorage.getItem('vastra_authenticated')==='true',name=profile.name||'Anil';const menu=document.createElement('section');menu.id='accountMenu';menu.className='account-menu';menu.innerHTML=logged?`<div class="account-welcome"><b>Hello ${name}</b><span>${id||'Welcome back'}</span></div><div class="account-links"><a href="/profile">Profile Details</a><a href="/orders">Orders</a><a href="/wishlist.html">Wishlist</a><a href="/account.html?section=coupons">Coupons</a></div><div class="account-links"><a href="/account.html?section=addresses">Saved Addresses</a><a href="/profile-edit">Edit Profile</a><a href="/login" data-logout>Logout</a></div>`:`<div class="account-welcome"><b>Welcome</b><span>To access account and manage orders</span><button class="login-signup" type="button">LOGIN / SIGNUP</button></div>`;document.body.appendChild(menu);menu.querySelector('.login-signup')?.addEventListener('click',()=>{location.href='/login'});menu.querySelector('[data-logout]')?.addEventListener('click',()=>localStorage.removeItem('vastra_authenticated'))};})();
document.querySelector('#wishlistBtn')?.addEventListener('click',()=>{location.href='/wishlist.html'});
/* Capture wishlist clicks before the frequent product refresh can replace the button. */
document.addEventListener('click',e=>{const b=e.target.closest('[data-wish]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();toggleWish(b.dataset.wish)},true);
const staticSearch=document.querySelector('#headerSearchInput');
if(staticSearch){const resultBox=document.querySelector('#headerSearchResults');staticSearch.addEventListener('input',()=>{const q=staticSearch.value.toLowerCase().trim();if(!q){resultBox.classList.remove('open');resultBox.innerHTML='';return}const matches=products.filter(p=>(p.name+' '+p.category+' '+(p.sku||'')).toLowerCase().includes(q)).slice(0,8);resultBox.innerHTML=matches.map(p=>'<a href="/product.html?sku='+encodeURIComponent(p.sku||p.id)+'"><span>'+p.name+'</span><small>'+p.category+' · ₹'+p.price+'</small><b>→</b></a>').join('')||'<p>No products found</p>';resultBox.classList.add('open')});document.addEventListener('click',e=>{if(!staticSearch.parentElement.contains(e.target))resultBox.classList.remove('open')})}
/* Keep catalog IDs stable across the admin sync loop so cart/wishlist never lose items. */
let normalizedCatalogSignature='';
setInterval(()=>{const next=products.map(p=>({...p,id:p.sku||p.id}));const sig=next.map(p=>p.id).join('|');if(sig!==normalizedCatalogSignature){normalizedCatalogSignature=sig;products=next;renderProducts()}},500);
if(location.protocol==='file:'){location.href='http://localhost:3000/#shop'}
setInterval(decorateProductGalleries,500);decorateProductGalleries();
fetch('/api/products',{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(rows=>{if(!Array.isArray(rows))return;const bySku=new Map(rows.map(x=>[String(x.sku),x]));products=products.map(p=>{const x=bySku.get(String(p.sku));return x?{...p,image_url:x.image_url,image_urls:x.image_urls,stock:Number(x.stock||0)}:p});renderProducts();decorateProductGalleries()}).catch(()=>{});

/* Live Supabase image hydration: render saved product images on storefront. */
(()=>{
  const urls=p=>{let a=[];try{a=Array.isArray(p?.image_urls)?p.image_urls:JSON.parse(p?.image_urls||'[]')}catch(e){}if(!a.length&&p?.image_url)a=[p.image_url];return a.filter(Boolean)};
  const hydrate=()=>document.querySelectorAll('.product-card').forEach(card=>{if(card.querySelector('.live-product-image,.card-gallery'))return;const b=card.querySelector('[data-add]'),p=products.find(x=>String(x.id)===String(b?.dataset.add)),a=urls(p),box=card.querySelector('.product-image'),art=box?.querySelector('.product-art');if(!p||!a.length||!box||!art)return;if(a.length===1){const im=document.createElement('img');im.className='live-product-image';im.src=a[0];im.alt=p.name;im.style='width:100%;height:100%;object-fit:cover;display:block';art.replaceWith(im);return}const g=document.createElement('div');g.className='card-gallery';g.innerHTML=a.map((u,i)=>'<img class="card-gallery-image '+(!i?'active':'')+'" src="'+u+'" alt="'+p.name+'">').join('')+'<button type="button" class="card-gallery-prev">‹</button><button type="button" class="card-gallery-next">›</button><span class="card-gallery-count">1/'+a.length+'</span>';art.replaceWith(g);let i=0;const show=d=>{i=(i+d+a.length)%a.length;g.querySelectorAll('.card-gallery-image').forEach((x,n)=>x.classList.toggle('active',n===i));g.querySelector('.card-gallery-count').textContent=(i+1)+'/'+a.length};g.querySelector('.card-gallery-prev').onclick=e=>{e.stopPropagation();show(-1)};g.querySelector('.card-gallery-next').onclick=e=>{e.stopPropagation();show(1)}});
  setInterval(hydrate,700);hydrate();
})();

/* Final storefront image source: always read Supabase directly; never depend on missing /api/products. */
(async()=>{try{const K='sb_publishable_NaR11hPva6us_0wX2fNamA_PWJ_YFR8',rows=await fetch('https://trnzlkcdjjltphkknrqv.supabase.co/rest/v1/products?select=*&status=eq.active&order=created_at.desc',{headers:{apikey:K,Authorization:'Bearer '+K}}).then(r=>r.json());if(!Array.isArray(rows)||!rows.length)return;products=rows.map((p,i)=>({id:p.sku||p.id,sku:p.sku,name:p.name,category:p.category||'Vastra edit',price:Number(p.price),mrp:Number(p.mrp||p.price),stock:Number(p.stock||0),image_url:p.image_url,image_urls:p.image_urls,colors:[['#8c3038','#d4a461'],['#b76b57','#eed2a7'],['#b4aa94','#6f7764'],['#6d1e2e','#d4b27c']][i%4],tag:i<2?'New':''}));const old=renderProducts;renderProducts=()=>{old();document.querySelectorAll('.product-card').forEach(c=>{const p=products.find(x=>String(x.id)===String(c.querySelector('[data-add]')?.dataset.add));let a=[];try{a=Array.isArray(p?.image_urls)?p.image_urls:JSON.parse(p?.image_urls||'[]')}catch(e){}if(!a.length&&p?.image_url)a=[p.image_url];const art=c.querySelector('.product-art');if(art&&a.length){const im=document.createElement('img');im.src=a[0];im.alt=p.name;im.style='width:100%;height:100%;object-fit:cover;display:block';art.replaceWith(im)}})};renderProducts()}catch(e){console.warn('live catalog',e)}})();
/* Search fix: live suggestions and keyword filtering. */
(()=>{const i=document.querySelector('#headerSearchInput'),b=document.querySelector('#headerSearchResults');if(!i||!b)return;const n=x=>String(x||'').toLowerCase().replace(/[^a-z0-9]+/g,'');const ok=(p,q)=>n([p.name,p.category,p.sku,p.id].join(' ')).includes(n(q));const go=()=>{let q=i.value.trim();if(!q){b.innerHTML='';b.classList.remove('open');document.querySelectorAll('#productGrid .product-card').forEach(x=>x.style.display='');return}let a=products.filter(p=>ok(p,q));b.innerHTML=a.slice(0,8).map(p=>'<a href="/product.html?sku='+encodeURIComponent(p.sku||p.id)+'"><span>'+p.name+'</span><small>'+p.category+' · ₹'+p.price+'</small></a>').join('')||'<p>No products found</p>';b.classList.add('open');document.querySelectorAll('#productGrid .product-card').forEach(c=>{let p=products.find(x=>String(x.id)===String(c.querySelector('[data-add]')?.dataset.add));c.style.display=p&&ok(p,q)?'':'none'})};i.oninput=go;go()})();
/* Search fix: live suggestions and keyword filtering. */
(()=>{const i=document.querySelector('#headerSearchInput'),b=document.querySelector('#headerSearchResults');if(!i||!b)return;const n=x=>String(x||'').toLowerCase().replace(/[^a-z0-9]+/g,'');const ok=(p,q)=>n([p.name,p.category,p.sku,p.id].join(' ')).includes(n(q));const go=()=>{let q=i.value.trim();if(!q){b.innerHTML='';b.classList.remove('open');document.querySelectorAll('#productGrid .product-card').forEach(x=>x.style.display='');return}let a=products.filter(p=>ok(p,q));b.innerHTML=a.slice(0,8).map(p=>'<a href="/product.html?sku='+encodeURIComponent(p.sku||p.id)+'"><span>'+p.name+'</span><small>'+p.category+' · ₹'+p.price+'</small></a>').join('')||'<p>No products found</p>';b.classList.add('open');document.querySelectorAll('#productGrid .product-card').forEach(c=>{let p=products.find(x=>String(x.id)===String(c.querySelector('[data-add]')?.dataset.add));c.style.display=p&&ok(p,q)?'':'none'})};i.oninput=go;go()})();
/* Rendered-card search fallback */(()=>{const i=document.querySelector('#headerSearchInput'),b=document.querySelector('#headerSearchResults');if(!i||!b)return;const go=()=>{const q=i.value.trim().toLowerCase(),cs=[...document.querySelectorAll('#productGrid .product-card')];if(!q){b.innerHTML='';b.classList.remove('open');cs.forEach(c=>c.style.display='');return}const h=cs.filter(c=>(c.innerText||'').toLowerCase().includes(q));b.innerHTML=h.slice(0,8).map(c=>{const a=c.querySelector('[data-add]'),n=c.querySelector('.product-name')?.textContent||'';return '<a href="/product.html?sku='+encodeURIComponent(a?.dataset.add||'')+'"><span>'+n+'</span></a>'}).join('')||'<p>No products found</p>';b.classList.add('open');cs.forEach(c=>c.style.display=h.includes(c)?'':'none')};i.oninput=go;go()})();
