let products=[
 {id:1,name:'Narayanpeta Buttis',category:'Dress Materials',price:1299,mrp:1699,colors:['#8c3038','#d4a461'],tag:'Bestseller'},
 {id:2,name:'Gulab Handloom Saree',category:'Sarees',price:2890,mrp:3490,colors:['#b76b57','#eed2a7'],tag:'New'},
 {id:3,name:'Mogra Cotton Kurti',category:'Kurtis',price:1490,mrp:1890,colors:['#b4aa94','#6f7764'],tag:''},
 {id:4,name:'Meher Chanderi Dupatta',category:'Dupattas',price:990,mrp:1290,colors:['#6d1e2e','#d4b27c'],tag:'New'},
 {id:5,name:'Rangoli Silk Saree',category:'Sarees',price:3290,mrp:4190,colors:['#4d526d','#d2a866'],tag:''},
 {id:6,name:'Noor Embroidered Kurta',category:'Kurtis',price:1790,mrp:2190,colors:['#c28b76','#f1d7bc'],tag:''},
 {id:7,name:'Ira Blockprint Set',category:'Dress Materials',price:1890,mrp:2390,colors:['#65715a','#e5c09b'],tag:'Bestseller'},
 {id:8,name:'Kali Zari Dupatta',category:'Dupattas',price:1190,mrp:1490,colors:['#aa6b41','#e5b974'],tag:''}
];
let activeCategory='All', cart=JSON.parse(localStorage.getItem('vastra-cart')||'[]'), wishlist=JSON.parse(localStorage.getItem('vastra-wishlist')||'[]');
fetch('https://trnzlkcdjjltphkknrqv.supabase.co/rest/v1/products?select=*&status=eq.active&order=created_at.desc',{headers:{apikey:'sb_publishable_NaR11hPva6us_0wX2fNamA_PWJ_YFR8',Authorization:'Bearer sb_publishable_NaR11hPva6us_0wX2fNamA_PWJ_YFR8'}}).then(r=>r.ok?r.json():[]).then(rows=>{if(rows.length){products=rows.map((p,i)=>({id:p.id,name:p.name,category:p.category||'Vastra edit',price:Number(p.price),mrp:Number(p.mrp),colors:[['#8c3038','#d4a461'],['#b76b57','#eed2a7'],['#b4aa94','#6f7764'],['#6d1e2e','#d4b27c']][i%4],tag:i<2?'New':''}));renderProducts();updateCart()}}).catch(()=>{});
const money=n=>'₹'+n.toLocaleString('en-IN');
function renderProducts(){let list=products.filter(p=>activeCategory==='All'||p.category===activeCategory);const sort=document.querySelector('#sortSelect').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);document.querySelector('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><div class="product-art" style="--p:${p.colors[0]};--q:${p.colors[1]}"></div><button class="heart ${wishlist.includes(p.id)?'active':''}" data-wish="${p.id}">${wishlist.includes(p.id)?'♥':'♡'}</button>${p.tag?`<span class="tag">${p.tag}</span>`:''}</div><div class="product-meta"><div><div class="product-name">${p.name}</div><div class="product-category">${p.category} · ★ 4.8</div></div><div class="product-price">${money(p.price)}<span class="mrp">${money(p.mrp)}</span></div></div><button class="quick-add" data-add="${p.id}">Quick add +</button></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(+b.dataset.wish));}
function save(){localStorage.setItem('vastra-cart',JSON.stringify(cart));localStorage.setItem('vastra-wishlist',JSON.stringify(wishlist));updateCart();}
function add(id){const found=cart.find(x=>x.id===id);found?found.qty++:cart.push({id,qty:1});save();toast('Added to your bag');}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();renderProducts();toast(wishlist.includes(id)?'Saved to wishlist':'Removed from wishlist');}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#drawerCount').textContent=count;const items=document.querySelector('#cartItems');if(!cart.length){items.innerHTML='<div class="empty">Your bag is waiting.<br><a href="#shop">Discover the edit →</a></div>';document.querySelector('#cartTotal').textContent='₹0';return}let total=0;items.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);total+=p.price*x.qty;return `<div class="cart-item"><div class="cart-thumb" style="--p:${p.colors[0]}"></div><div><h4>${p.name}</h4><small>${p.category} · ${money(p.price)}</small><div class="qty"><button data-dec="${p.id}">−</button>${x.qty}<button data-inc="${p.id}">+</button><button class="remove" data-remove="${p.id}">Remove</button></div></div></div>`}).join('');document.querySelector('#cartTotal').textContent=money(total);items.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>change(+b.dataset.inc,1));items.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>change(+b.dataset.dec,-1));items.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);save()});}
function change(id,delta){const x=cart.find(y=>y.id===id);x.qty+=delta;if(x.qty<1)cart=cart.filter(y=>y.id!==id);save()}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openCart(){document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#overlay').classList.add('show')};function closeCart(){document.querySelector('#cartDrawer').classList.remove('open');document.querySelector('#overlay').classList.remove('show')}
document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#closeCart').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#sortSelect').onchange=renderProducts;document.querySelector('#filterBtn').onclick=()=>document.querySelector('#filterRow').classList.toggle('open');document.querySelectorAll('.filter-row button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.cat;renderProducts()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.filter;document.querySelectorAll('.filter-row button').forEach(x=>x.classList.toggle('active',x.dataset.cat===activeCategory));renderProducts()});document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();document.querySelector('#newsletterMsg').textContent='You’re on the list — welcome to Vastra.';e.target.reset()};document.querySelector('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Your bag is empty');toast('Checkout is ready for Razorpay + COD setup')};renderProducts();updateCart();
document.body.insertAdjacentHTML('beforeend','<div class="modal" id="detailModal"><div class="modal-card" id="detailContent"></div></div><div class="modal" id="checkoutModal"><div class="modal-card checkout-card"><button class="close-btn modal-close">×</button><p class="eyebrow">SECURE CHECKOUT</p><h2>Complete your order.</h2><form id="checkoutForm"><label>Full name<input required name="name" placeholder="Your name"></label><label>Email address<input required type="email" name="email" placeholder="you@example.com"></label><label>Delivery address<textarea required name="address" placeholder="House no., street, city, state"></textarea></label><label>Pincode<input required pattern="[0-9]{6}" name="pincode" placeholder="6-digit pincode"></label><p class="eyebrow">PAYMENT METHOD</p><label><input type="radio" name="payment" value="cod" checked> Cash on Delivery</label><label><input type="radio" name="payment" value="razorpay"> Razorpay (integration ready)</label><button class="btn btn-dark full">Place order <span>→</span></button><small class="muted">Totals, stock and payment status must be verified server-side.</small></form></div></div>');
function openDetail(id){const p=products.find(x=>x.id===id);document.querySelector('#detailContent').innerHTML='<button class="close-btn modal-close">×</button><div class="detail-layout"><div class="detail-visual" style="--p:'+p.colors[0]+';--q:'+p.colors[1]+'"><div class="product-art"></div></div><div class="detail-copy"><p class="eyebrow">'+p.category.toUpperCase()+' · VASTRA</p><h2>'+p.name+'</h2><p class="product-rating">★ 4.8 · 24 reviews</p><div class="detail-price">'+money(p.price)+' <span>'+money(p.mrp)+'</span> <b>'+Math.round((1-p.price/p.mrp)*100)+'% off</b></div><p class="detail-description">A considered piece made for celebration and everyday ritual. Finished with a soft handfeel, thoughtful detail and the unmistakable character of Indian craft.</p><div class="detail-specs"><span>Fabric <b>Premium cotton blend</b></span><span>Dispatch <b>Within 2–3 days</b></span></div><button class="btn btn-dark full" data-detail-add="'+p.id+'">Add to bag <span>→</span></button></div></div>';document.querySelector('#detailModal').classList.add('show');document.querySelectorAll('.modal-close').forEach(x=>x.onclick=()=>document.querySelector('#detailModal').classList.remove('show'));document.querySelector('[data-detail-add]').onclick=()=>{add(id);document.querySelector('#detailModal').classList.remove('show')}}
document.querySelector('#productGrid').addEventListener('click',e=>{const card=e.target.closest('.product-card');if(card&&!e.target.closest('button'))openDetail(+card.querySelector('[data-add]').dataset.add)});
document.querySelector('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Your bag is empty');closeCart();document.querySelector('#checkoutModal').classList.add('show')};document.querySelector('#checkoutModal').addEventListener('click',e=>{if(e.target.id==='checkoutModal'||e.target.closest('.modal-close'))document.querySelector('#checkoutModal').classList.remove('show')});document.querySelector('#checkoutForm').onsubmit=e=>{e.preventDefault();cart=[];save();document.querySelector('#checkoutModal').classList.remove('show');toast('Order received — thank you for choosing Vastra')};
