const http=require('http'),fs=require('fs'),path=require('path'),url=require('url');
const root=__dirname,seed=JSON.parse(fs.readFileSync(path.join(root,'db','seed.json'),'utf8'));let state={...seed,orders:[],users:[],reviews:[]};function env(name){try{const line=fs.readFileSync(path.join(root,'.env.local'),'utf8').split(/\r?\n/).find(x=>x.startsWith(name+'='));return line?.slice(name.length+1).trim()}catch{return process.env[name]}}
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.sql':'text/plain'};
function send(res,status,data,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(data):data)}
function body(req){return new Promise(resolve=>{let d='';req.on('data',x=>d+=x);req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch{resolve({})}})})}
const server=http.createServer(async(req,res)=>{const p=url.parse(req.url,true).pathname;
if(p.startsWith('/api/')){
if(req.method==='GET'&&p==='/api/cloudinary-config')return send(res,200,{cloudName:env('CLOUDINARY_CLOUD_NAME')||'',uploadPreset:env('CLOUDINARY_UPLOAD_PRESET')||'',enabled:env('CLOUDINARY_ENABLED')==='true'});
if(req.method==='GET'&&p==='/api/products')return send(res,200,state.products.map(x=>({...x,id:x.id||x.sku})));
if(req.method==='GET'&&p==='/api/orders')return send(res,200,state.orders);
if(req.method==='GET'&&p==='/api/categories')return send(res,200,state.categories);
if(req.method==='GET'&&p==='/api/admin/metrics')return send(res,200,{products:state.products.length,orders:state.orders.length,customers:state.users.length,lowStock:state.products.filter(x=>x.stock<10).length,sales:state.orders.reduce((s,x)=>s+x.total,0)});
if(req.method==='POST'&&p==='/api/orders'){const b=await body(req),items=(b.items||[]).map(x=>{const product=state.products.find(y=>y.sku===x.sku||String(y.id)===String(x.id));return {...x,product,price:product?.price||0}});if(!items.length||items.some(x=>!x.product||x.quantity>x.product.stock||x.product.status==='disabled'))return send(res,400,{error:'Product unavailable or insufficient stock'});const subtotal=items.reduce((s,x)=>s+x.price*x.quantity,0),order={id:state.orders.length+1,orderNumber:'VAS-'+Date.now(),status:'pending',paymentStatus:'pending',paymentMethod:b.paymentMethod||'cod',customer:b.customer||{},items:items.map(x=>({sku:x.product.sku,name:x.product.name,quantity:x.quantity,price:x.price})),subtotal,total:subtotal,createdAt:new Date().toISOString()};items.forEach(x=>x.product.stock-=x.quantity);state.orders.push(order);return send(res,201,order)}
if(p.startsWith('/api/products/')){const id=p.split('/').pop(),product=state.products.find(x=>String(x.id)===id||x.sku===id);if(!product)return send(res,404,{error:'Product not found'});if(req.method==='DELETE'){state.products=state.products.filter(x=>x!==product);return send(res,200,{ok:true})}if(req.method==='PATCH'){const b=await body(req);Object.assign(product,{name:b.name??product.name,price:b.price??product.price,mrp:b.mrp??product.mrp,stock:b.stock??product.stock,status:b.status??product.status,category:b.category??product.category,description:b.description??product.description,imageUrl:b.imageUrl??product.imageUrl});return send(res,200,product)}}
return send(res,404,{error:'API route not found'})}
let file=p==='/'?'index.html':p.slice(1);if(file==='admin')file='admin.html';if(file==='login')file='login.html';if(file==='profile')file='profile.html';if(file==='profile-edit')file='profile-edit.html';if(file==='orders')file='orders.html';const full=path.join(root,file);if(fs.existsSync(full)){let data=fs.readFileSync(full);if(file==='admin.html')data=Buffer.from(data.toString().replace('</body>','<script src="/admin-price.js"></script></body>'));if(file==='product.html')data=Buffer.from(data.toString().replace('</body>','<script src="/product-price.js"></script><script src="/product-gallery.js"></script></body>'));return send(res,200,data,mime[path.extname(full)]||'text/plain')}send(res,404,'Not found','text/plain')});server.listen(3000,()=>console.log('Vastra running at http://localhost:3000'));
